//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{


     public partial class WebForm5
     {

          /// <summary>
          /// fileUpload1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.FileUpload fileUpload1;

          /// <summary>
          /// btnCalculateGrade control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnCalculateGrade;

          /// <summary>
          /// UploadStatusLabel control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label UploadStatusLabel;

          /// <summary>
          /// lblNumPages control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblNumPages;

          /// <summary>
          /// lblSearchPhraseCount control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblSearchPhraseCount;

          /// <summary>
          /// lblBuzzwords control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblBuzzwords;

          /// <summary>
          /// lblErrorCount control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblErrorCount;

          /// <summary>
          /// lblError control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblError;

          /// <summary>
          /// lblGrade control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblGrade;

          /// <summary>
          /// lblKeyword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblKeyword;

          /// <summary>
          /// lblKeywordCount control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblKeywordCount;
     }
}
