//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{


     public partial class TemplateEditor
     {

          /// <summary>
          /// container control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl container;

          /// <summary>
          /// row1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl row1;

          /// <summary>
          /// col1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl col1;

          /// <summary>
          /// card control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl card;

          /// <summary>
          /// cardBody control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardBody;

          /// <summary>
          /// titleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl titleRow;

          /// <summary>
          /// titleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl titleColumn;

          /// <summary>
          /// header1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl header1;

          /// <summary>
          /// contactInfoTitleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl contactInfoTitleRow;

          /// <summary>
          /// contactInfoTitleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl contactInfoTitleColumn;

          /// <summary>
          /// contactinfotitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl contactinfotitle;

          /// <summary>
          /// nameInfo control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl nameInfo;

          /// <summary>
          /// nameInfoColumn1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl nameInfoColumn1;

          /// <summary>
          /// lblTE_FirstName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_FirstName;

          /// <summary>
          /// txtTE_FirstName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_FirstName;

          /// <summary>
          /// rfvTE_FirstName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_FirstName;

          /// <summary>
          /// nameInfoColumn2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl nameInfoColumn2;

          /// <summary>
          /// lblTE_LastName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_LastName;

          /// <summary>
          /// txtTE_LastName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_LastName;

          /// <summary>
          /// rfvTE_LastName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_LastName;

          /// <summary>
          /// contactInfo control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl contactInfo;

          /// <summary>
          /// phoneColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl phoneColumn;

          /// <summary>
          /// lblTE_PhoneNum control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_PhoneNum;

          /// <summary>
          /// txtTE_PhoneNum control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_PhoneNum;

          /// <summary>
          /// rfvTE_PhoneNum control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_PhoneNum;

          /// <summary>
          /// emailColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl emailColumn;

          /// <summary>
          /// lblTE_Email control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Email;

          /// <summary>
          /// txtTE_Email control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Email;

          /// <summary>
          /// rfvTE_Email control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Email;

          /// <summary>
          /// homeAddressTitleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeAddressTitleRow;

          /// <summary>
          /// homeAddressTitleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeAddressTitleColumn;

          /// <summary>
          /// homeaddresstitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeaddresstitle;

          /// <summary>
          /// homeAddressRowTitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeAddressRowTitle;

          /// <summary>
          /// homeAddressColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeAddressColumn;

          /// <summary>
          /// lblTE_Address control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Address;

          /// <summary>
          /// txtTE_Address control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Address;

          /// <summary>
          /// rfvTE_Address control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Address;

          /// <summary>
          /// homeAddressRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeAddressRow;

          /// <summary>
          /// homeCityColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeCityColumn;

          /// <summary>
          /// lblTE_City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_City;

          /// <summary>
          /// txtTE_City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_City;

          /// <summary>
          /// rfvTE_City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_City;

          /// <summary>
          /// homeStateColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeStateColumn;

          /// <summary>
          /// lblTE_State control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_State;

          /// <summary>
          /// txtTE_State control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_State;

          /// <summary>
          /// rfvTE_State control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_State;

          /// <summary>
          /// homeZipColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl homeZipColumn;

          /// <summary>
          /// lblTE_Zip control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Zip;

          /// <summary>
          /// txtTE_Zip control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Zip;

          /// <summary>
          /// rfvTE_Zip control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Zip;

          /// <summary>
          /// summarystatementrow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl summarystatementrow;

          /// <summary>
          /// summarystatementcolumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl summarystatementcolumn;

          /// <summary>
          /// summarystatementtitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl summarystatementtitle;

          /// <summary>
          /// summarystatementblock control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl summarystatementblock;

          /// <summary>
          /// txtTE_Summary control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Summary;

          /// <summary>
          /// rfvTE_Summary control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Summary;

          /// <summary>
          /// objectiveTitleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl objectiveTitleRow;

          /// <summary>
          /// objectiveTitleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl objectiveTitleColumn;

          /// <summary>
          /// objectiveTitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl objectiveTitle;

          /// <summary>
          /// objective control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl objective;

          /// <summary>
          /// txtTE_Objective control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Objective;

          /// <summary>
          /// rfvTE_Objective control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Objective;

          /// <summary>
          /// professionalSkillsTitleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl professionalSkillsTitleRow;

          /// <summary>
          /// professionalSkillsTitleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl professionalSkillsTitleColumn;

          /// <summary>
          /// professionalskillstitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl professionalskillstitle;

          /// <summary>
          /// professionalSkills control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl professionalSkills;

          /// <summary>
          /// skill1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill1;

          /// <summary>
          /// skill1label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill1label;

          /// <summary>
          /// txtTE_Skill1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill1;

          /// <summary>
          /// rfvTE_Skill1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill1;

          /// <summary>
          /// skill2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill2;

          /// <summary>
          /// skill2label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill2label;

          /// <summary>
          /// txtTE_Skill2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill2;

          /// <summary>
          /// rfvTE_Skill2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill2;

          /// <summary>
          /// skill3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill3;

          /// <summary>
          /// skill3label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill3label;

          /// <summary>
          /// txtTE_Skill3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill3;

          /// <summary>
          /// rfvTE_Skill3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill3;

          /// <summary>
          /// skill4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill4;

          /// <summary>
          /// skill4label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill4label;

          /// <summary>
          /// txtTE_Skill4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill4;

          /// <summary>
          /// rfvTE_Skill4 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill4;

          /// <summary>
          /// skill5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill5;

          /// <summary>
          /// skill5label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill5label;

          /// <summary>
          /// txtTE_Skill5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill5;

          /// <summary>
          /// rfvTE_Skill5 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill5;

          /// <summary>
          /// skill6 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill6;

          /// <summary>
          /// skill6label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill6label;

          /// <summary>
          /// txtTE_Skill6 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill6;

          /// <summary>
          /// rfvTE_Skill6 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill6;

          /// <summary>
          /// skill7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill7;

          /// <summary>
          /// skill7label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill7label;

          /// <summary>
          /// txtTE_Skill7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill7;

          /// <summary>
          /// rfvTE_Skill7 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill7;

          /// <summary>
          /// skill8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill8;

          /// <summary>
          /// skill8label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill8label;

          /// <summary>
          /// txtTE_Skill8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill8;

          /// <summary>
          /// rfvTE_Skill8 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill8;

          /// <summary>
          /// skill9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl skill9;

          /// <summary>
          /// skill9label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label skill9label;

          /// <summary>
          /// txtTE_Skill9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Skill9;

          /// <summary>
          /// rfvTE_Skill9 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Skill9;

          /// <summary>
          /// workExperienceTitleRow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl workExperienceTitleRow;

          /// <summary>
          /// workExperienceTitleColumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl workExperienceTitleColumn;

          /// <summary>
          /// workExperienceTitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl workExperienceTitle;

          /// <summary>
          /// job1block control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job1block;

          /// <summary>
          /// job1info control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job1info;

          /// <summary>
          /// lblTE_Job1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job1;

          /// <summary>
          /// lblTE_Company1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company1;

          /// <summary>
          /// txtTE_Company1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company1;

          /// <summary>
          /// rfvTE_Company1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company1;

          /// <summary>
          /// job1location control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job1location;

          /// <summary>
          /// lblTE_Company1City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company1City;

          /// <summary>
          /// txtTE_Company1City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company1City;

          /// <summary>
          /// rfvTE_Company1City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company1City;

          /// <summary>
          /// lblTE_TimeWorked control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_TimeWorked;

          /// <summary>
          /// txtTE_TimeWorked control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_TimeWorked;

          /// <summary>
          /// rfvTE_TimeWorked control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_TimeWorked;

          /// <summary>
          /// lblTE_JobTitle1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_JobTitle1;

          /// <summary>
          /// txtTE_JobTitle1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_JobTitle1;

          /// <summary>
          /// rfvTE_JobTitle1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_JobTitle1;

          /// <summary>
          /// lblTE_Job1Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job1Responsibilities1;

          /// <summary>
          /// txtTE_Job1Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job1Responsibilities1;

          /// <summary>
          /// rfvTE_Job1Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job1Responsibilities1;

          /// <summary>
          /// lblTE_Job1Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job1Responsibilities2;

          /// <summary>
          /// txtTE_Job1Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job1Responsibilities2;

          /// <summary>
          /// rfvTE_Job1Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job1Responsibilities2;

          /// <summary>
          /// lblTE_Job1Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job1Responsibilities3;

          /// <summary>
          /// txtTE_Job1Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job1Responsibilities3;

          /// <summary>
          /// rfvTE_Job1Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job1Responsibilities3;

          /// <summary>
          /// job2block control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job2block;

          /// <summary>
          /// job2info control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job2info;

          /// <summary>
          /// job2label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label job2label;

          /// <summary>
          /// lblTE_Company2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company2;

          /// <summary>
          /// txtTE_Company2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company2;

          /// <summary>
          /// rfvTE_Company2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company2;

          /// <summary>
          /// job2location control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job2location;

          /// <summary>
          /// lblTE_Company2City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company2City;

          /// <summary>
          /// txtTE_Company2City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company2City;

          /// <summary>
          /// rfvTE_Company2City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company2City;

          /// <summary>
          /// lblTE_TimeWorked2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_TimeWorked2;

          /// <summary>
          /// txtTE_TimeWorked2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_TimeWorked2;

          /// <summary>
          /// rfvTE_TimeWorked2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_TimeWorked2;

          /// <summary>
          /// lblTE_JobTitle2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_JobTitle2;

          /// <summary>
          /// txtTE_JobTitle2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_JobTitle2;

          /// <summary>
          /// rfvTE_JobTitle2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_JobTitle2;

          /// <summary>
          /// lblTE_Job2Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job2Responsibilities1;

          /// <summary>
          /// txtTE_Job2Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job2Responsibilities1;

          /// <summary>
          /// rfvTE_Job2Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job2Responsibilities1;

          /// <summary>
          /// lblTE_Job2Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job2Responsibilities2;

          /// <summary>
          /// txtTE_Job2Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job2Responsibilities2;

          /// <summary>
          /// rfvTE_Job2Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job2Responsibilities2;

          /// <summary>
          /// lblTE_Job2Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job2Responsibilities3;

          /// <summary>
          /// txtTE_Job2Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job2Responsibilities3;

          /// <summary>
          /// rfvTE_Job2Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job2Responsibilities3;

          /// <summary>
          /// job3block control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job3block;

          /// <summary>
          /// job3info control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job3info;

          /// <summary>
          /// job3label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label job3label;

          /// <summary>
          /// lblTE_Company3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company3;

          /// <summary>
          /// txtTE_Company3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company3;

          /// <summary>
          /// rfvTE_Company3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company3;

          /// <summary>
          /// job3location control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl job3location;

          /// <summary>
          /// lblTE_Company3City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Company3City;

          /// <summary>
          /// txtTE_Company3City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Company3City;

          /// <summary>
          /// rfvTE_Company3City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Company3City;

          /// <summary>
          /// lblTE_TimeWorked3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_TimeWorked3;

          /// <summary>
          /// txtTE_Timeworked3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Timeworked3;

          /// <summary>
          /// rfvTE_TimeWorked3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_TimeWorked3;

          /// <summary>
          /// lblTE_JobTitle3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_JobTitle3;

          /// <summary>
          /// txtTE_JobTitle3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_JobTitle3;

          /// <summary>
          /// rfvTE_JobTitle3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_JobTitle3;

          /// <summary>
          /// lblTE_Job3Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job3Responsibilities1;

          /// <summary>
          /// txtTE_Job3Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job3Responsibilities1;

          /// <summary>
          /// rfvTE_Job3Responsibilities1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job3Responsibilities1;

          /// <summary>
          /// lblTE_Job3Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job3Responsibilities2;

          /// <summary>
          /// txtTE_Job3Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job3Responsibilities2;

          /// <summary>
          /// rfvTE_Job3Responsibilities2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job3Responsibilities2;

          /// <summary>
          /// lblTE_Job3Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Job3Responsibilities3;

          /// <summary>
          /// txtTE_Job3Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Job3Responsibilities3;

          /// <summary>
          /// rfvTE_Job3Responsibilities3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Job3Responsibilities3;

          /// <summary>
          /// educationtitlerow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl educationtitlerow;

          /// <summary>
          /// educationtitlecolumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl educationtitlecolumn;

          /// <summary>
          /// educationtitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl educationtitle;

          /// <summary>
          /// education1block control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl education1block;

          /// <summary>
          /// school1label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label school1label;

          /// <summary>
          /// lblTE_School control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_School;

          /// <summary>
          /// txtTE_School control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_School;

          /// <summary>
          /// rfvTE_School control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_School;

          /// <summary>
          /// school1location control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl school1location;

          /// <summary>
          /// lblTE_SchoolCity control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_SchoolCity;

          /// <summary>
          /// txtTE_SchoolCity control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_SchoolCity;

          /// <summary>
          /// rfvTE_SchoolCity control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_SchoolCity;

          /// <summary>
          /// lblTE_GradDate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_GradDate;

          /// <summary>
          /// txtTE_GradDate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_GradDate;

          /// <summary>
          /// rfvTE_GradDate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_GradDate;

          /// <summary>
          /// GPAblock control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl GPAblock;

          /// <summary>
          /// lblTE_GPA control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_GPA;

          /// <summary>
          /// txtTE_GPA control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_GPA;

          /// <summary>
          /// rfvTE_GPA control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_GPA;

          /// <summary>
          /// extracurricularsblock control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl extracurricularsblock;

          /// <summary>
          /// lblTE_Extracaricular1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Extracaricular1;

          /// <summary>
          /// txtTE_Extracaricular1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Extracaricular1;

          /// <summary>
          /// rfvTE_Extracaricular1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Extracaricular1;

          /// <summary>
          /// extracurricular1details control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl extracurricular1details;

          /// <summary>
          /// lblTE_Extracaricular1Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Extracaricular1Detail;

          /// <summary>
          /// txtTE_Extracaricular1Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Extracaricular1Detail;

          /// <summary>
          /// rfvTE_Extracaricular1Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Extracaricular1Detail;

          /// <summary>
          /// lblTE_Extracaricular2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Extracaricular2;

          /// <summary>
          /// txtTE_Extracaricular2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Extracaricular2;

          /// <summary>
          /// rfvTE_Extracaricular2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Extracaricular2;

          /// <summary>
          /// extracurricular2details control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl extracurricular2details;

          /// <summary>
          /// lblTE_Extracaricular2Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Extracaricular2Detail;

          /// <summary>
          /// txtTE_Extracaricular2Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Extracaricular2Detail;

          /// <summary>
          /// rfvTE_Extracaricular2Detail control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Extracaricular2Detail;

          /// <summary>
          /// degree control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl degree;

          /// <summary>
          /// lblTE_Degree control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label lblTE_Degree;

          /// <summary>
          /// txtTE_Degree control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_Degree;

          /// <summary>
          /// rfvTE_Degree control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_Degree;

          /// <summary>
          /// additionalskillstitlerow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl additionalskillstitlerow;

          /// <summary>
          /// additionalskillstitlecolumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl additionalskillstitlecolumn;

          /// <summary>
          /// additionalskillstitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl additionalskillstitle;

          /// <summary>
          /// additionalskillsblock control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl additionalskillsblock;

          /// <summary>
          /// additionalskill1label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label additionalskill1label;

          /// <summary>
          /// txtTE_AddSkill1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_AddSkill1;

          /// <summary>
          /// rfvTE_AddSkill1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_AddSkill1;

          /// <summary>
          /// additionalskill2label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label additionalskill2label;

          /// <summary>
          /// txtTE_AddSkill2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_AddSkill2;

          /// <summary>
          /// rfvTE_AddSkill2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_AddSkill2;

          /// <summary>
          /// awardsandcertstitlerow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl awardsandcertstitlerow;

          /// <summary>
          /// awardsandcertstitlecolumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl awardsandcertstitlecolumn;

          /// <summary>
          /// awardsandcertstitle control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl awardsandcertstitle;

          /// <summary>
          /// awardsandcertsblock control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl awardsandcertsblock;

          /// <summary>
          /// awardcert1label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label awardcert1label;

          /// <summary>
          /// txtTE_AwCert1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_AwCert1;

          /// <summary>
          /// rfvTE_AwCert1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_AwCert1;

          /// <summary>
          /// awardcert2label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label awardcert2label;

          /// <summary>
          /// txtTE_AwCert2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_AwCert2;

          /// <summary>
          /// rfvTE_AwCert2 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_AwCert2;

          /// <summary>
          /// awardcert3label control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label awardcert3label;

          /// <summary>
          /// txtTE_AwCert3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtTE_AwCert3;

          /// <summary>
          /// rfvTE_AwCert3 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTE_AwCert3;

          /// <summary>
          /// downloadbuttonrow control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl downloadbuttonrow;

          /// <summary>
          /// downloadbuttoncolumn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl downloadbuttoncolumn;

          /// <summary>
          /// btnDownload control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnDownload;

          /// <summary>
          /// Master property.
          /// </summary>
          /// <remarks>
          /// Auto-generated property.
          /// </remarks>
          public new Test.HomeDemo Master
          {
               get
               {
                    return ((Test.HomeDemo)(base.Master));
               }
          }
     }
}
