//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{


     public partial class WebForm3
     {

          /// <summary>
          /// Dashboard control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl Dashboard;

          /// <summary>
          /// UserDashboard control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl UserDashboard;

          /// <summary>
          /// AccUpdate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl AccUpdate;

          /// <summary>
          /// txtUD_FullName control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_FullName;

          /// <summary>
          /// txtUD_DateOfBirth control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_DateOfBirth;

          /// <summary>
          /// txtUD_ContactNum control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_ContactNum;

          /// <summary>
          /// txtUD_Email control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_Email;

          /// <summary>
          /// ddlUD_State control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.DropDownList ddlUD_State;

          /// <summary>
          /// txtUD_City control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_City;

          /// <summary>
          /// txtUD_ZipCode control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_ZipCode;

          /// <summary>
          /// txtUD_Street control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_Street;

          /// <summary>
          /// txtUD_UserID control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_UserID;

          /// <summary>
          /// txtUD_OldPassword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_OldPassword;

          /// <summary>
          /// txtUD_NewPassword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUD_NewPassword;

          /// <summary>
          /// revNewPassword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RegularExpressionValidator revNewPassword;

          /// <summary>
          /// btnUpAcc control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnUpAcc;

          /// <summary>
          /// CheckResume control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl CheckResume;

          /// <summary>
          /// SavedTemplate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl SavedTemplate;

          /// <summary>
          /// templateimage control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlImage templateimage;

          /// <summary>
          /// btnContinueEdit control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnContinueEdit;

          /// <summary>
          /// TS_Warning control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl TS_Warning;

          /// <summary>
          /// DB_ChooseTemplate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl DB_ChooseTemplate;

          /// <summary>
          /// btnDiffTemplate control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnDiffTemplate;

          /// <summary>
          /// UploadResume control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl UploadResume;

          /// <summary>
          /// FU_DashBoard control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl FU_DashBoard;

          /// <summary>
          /// staticBackdropLabel control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.HtmlControls.HtmlGenericControl staticBackdropLabel;

          /// <summary>
          /// DB_FileUpLoad control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.FileUpload DB_FileUpLoad;

          /// <summary>
          /// FU_Message control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label FU_Message;

          /// <summary>
          /// Button1 control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button Button1;
     }
}
