//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{


     public partial class UserLogin
     {

          /// <summary>
          /// txtUsername control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtUsername;

          /// <summary>
          /// rfvUsername control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;

          /// <summary>
          /// txtPassword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.TextBox txtPassword;

          /// <summary>
          /// rfvPassword control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

          /// <summary>
          /// loginError control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Label loginError;

          /// <summary>
          /// btnLogIn control.
          /// </summary>
          /// <remarks>
          /// Auto-generated field.
          /// To modify move field declaration from designer file to code-behind file.
          /// </remarks>
          protected global::System.Web.UI.WebControls.Button btnLogIn;

          /// <summary>
          /// Master property.
          /// </summary>
          /// <remarks>
          /// Auto-generated property.
          /// </remarks>
          public new Test.HomeDemo Master
          {
               get
               {
                    return ((Test.HomeDemo)(base.Master));
               }
          }
     }
}
